name: 'xero_integration_tests'
version: '1.0.0'
profile: 'integration_tests'
config-version: 2

vars: 
  xero_source:
    account: "{{ ref('xero_account_data') }}"
    bank_account: "{{ ref('xero_bank_account_data') }}"
    bank_transaction: "{{ ref('xero_bank_transaction_data') }}"
    contact: "{{ ref('xero_contact_data') }}"
    invoice_line_item: "{{ ref('xero_invoice_line_item_data') }}"
    invoice: "{{ ref('xero_invoice_data') }}"
    journal_line: "{{ ref('xero_journal_line_data') }}"
    journal: "{{ ref('xero_journal_data') }}"
    manual_journal_line: "{{ ref('xero_manual_journal_line_data') }}"
    manual_journal: "{{ ref('xero_manual_journal_data') }}"
    payment: "{{ ref('xero_payment_data') }}"